project:
  type: website
  output-dir: docs

website:
  title: "Kolkrabe"
  navbar: false
  sidebar:
    style: "docked"
    background: dark
    search: true
    contents:
      - text: "Welcome"
        href: index.qmd
      - section: "CCNP ENARSI"
        contents:
          - section: "Layer 3 Technologies"
            contents: 
              - bgp.qmd
              - eigrp.qmd
              - ospf.qmd
              - redistribution.qmd
              - routemap-pbr.qmd
              - vrf.qmd
          - section: "VPN & Encryption"
            contents:
              - mpls.qmd
              - dmvpn.qmd
              - gre+ipsec.qmd
          - section: "Infrastructure Services"
            contents:
              - device_management.qmd
              - logging.qmd
              - snmp.qmd
              - dhcp.qmd
              - ipsla+track.qmd
              - netflow.qmd
          - section: "Infrastructure Security"
            contents:
             - acls.qmd
             - aaa.qmd
             - uRPF.qmd
             - copp.qmd
             - ipv6sec.qmd
      - whitepapers.qmd
      - tools.qmd

format:
  html:
    theme: solar
    css: styles.css
    toc: true
